# Generated by Django 3.0.3 on 2020-03-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecar', '0003_rent_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red'), ('PINK', 'Pink'), ('ORANGE', 'Orange'), ('BLACK', 'Black'), ('WHITE', 'White'), ('SILVER', 'Silver'), ('BRONZ', 'Bronze'), ('YELLOW', 'Yellow')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NO AVAILABLE', 'Not Available'), ('HIDE', 'Hide')], max_length=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='type_gear',
            field=models.CharField(choices=[('AUTO', 'Manual Transmission'), ('MANUAL', 'Automatic Transmission'), ('CBT', 'CVT Transmission'), ('DTC', 'Semi-automatic and Dual-clutch Transmission (DCT)')], max_length=10),
        ),
    ]
