# Generated by Django 4.2.7 on 2023-11-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecar', '0018_alter_car_id_alter_promo_id_alter_rent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NO_AVAILABLE', 'Not Available'), ('HIDE', 'Hidden')], max_length=12),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('Picked', 'Car picked up'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Returned', 'Car returned'), ('Pending', 'Pending approval')], max_length=8),
        ),
    ]
